#!/usr/bin/env python3

import parser
import gui

if __name__ == '__main__':
    config = parser.configuration()

    if config['gui_mode'] == True:
        gui.display()
    else:
        parser.cli()

